apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app
  minReplicas: 2  # Minimum replicas for failover
  maxReplicas: 10  # Maximum replicas for scaling
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Target CPU utilization for scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50  # Target memory utilization for scaling
